{% set name = "fastuuid" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastuuid-{{ version }}.tar.gz
  sha256: d0bd4e5b35aad2826403f4411937c89e7c88857b1513fe10f696544c03e9bd8e

build:
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - maturin >=1.0,<2.0
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  imports:
    - fastuuid
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  summary: "Python bindings to Rust's UUID library."
  home: https://github.com/fastuuid/fastuuid
  license: BSD-3-Clause
  license_file: 
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jan-janssen
