{% set name = "fastuuid" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastuuid-{{ version }}.tar.gz
  sha256: d755dc132addb369877429622535dfb52d79c8968a8a98f15a84c3da1db013c7

build:
  number: 1
  skip: true  # [osx and py==310]
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - maturin >=1.0,<2.0
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python

test:
  imports:
    - fastuuid
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  summary: "Python bindings to Rust's UUID library."
  home: https://github.com/fastuuid/fastuuid
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jan-janssen
